//! File payload construction for external drag operations.
//!
//! This mirrors the payload formats accepted by common DAWs and file managers:
//! URI-list variants for DND-aware targets, a GNOME copied-files payload for
//! file managers, and plain path text for permissive hosts.

use std::path::{Path, PathBuf};

use percent_encoding::{AsciiSet, CONTROLS, utf8_percent_encode};

const URI_ESCAPE: &AsciiSet = &CONTROLS
    .add(b' ')
    .add(b'"')
    .add(b'#')
    .add(b'%')
    .add(b'<')
    .add(b'>')
    .add(b'?')
    .add(b'`')
    .add(b'{')
    .add(b'}');

/// Number of file offers generated by [`FileDragPayloadData::offers`].
#[cfg(test)]
const FILE_DRAG_OFFER_COUNT: usize = 7;

/// Standard file drag MIME type.
pub const MIME_TEXT_URI_LIST: &str = "text/uri-list";
/// UTF-8-labeled URI list MIME type used by some toolkits.
pub const MIME_TEXT_URI_LIST_UTF8: &str = "text/uri-list;charset=utf-8";
/// Alternate URI MIME type accepted by some DAWs and file managers.
pub const MIME_TEXT_X_URI: &str = "text/x-uri";
/// KDE URI list MIME type.
pub const MIME_KDE_URI_LIST: &str = "application/x-kde4-urilist";
/// GNOME/Nautilus copied-files payload MIME type.
pub const MIME_GNOME_COPIED_FILES: &str = "x-special/gnome-copied-files";
/// Plain path text MIME type.
pub const MIME_TEXT_PLAIN: &str = "text/plain";
/// UTF-8-labeled plain path text MIME type.
pub const MIME_TEXT_PLAIN_UTF8: &str = "text/plain;charset=utf-8";

/// One MIME offer and byte payload advertised during a file drag.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FileDragOffer {
    mime_type: &'static str,
    data: Vec<u8>,
}

impl FileDragOffer {
    /// Build a file drag offer.
    #[must_use]
    pub fn new(mime_type: &'static str, data: Vec<u8>) -> Self {
        Self { mime_type, data }
    }

    /// MIME type to advertise to the target.
    #[must_use]
    pub const fn mime_type(&self) -> &'static str {
        self.mime_type
    }

    /// Offer bytes.
    #[must_use]
    pub fn data(&self) -> &[u8] {
        &self.data
    }

    /// Consume the offer and return the owned bytes.
    #[must_use]
    pub fn into_data(self) -> Vec<u8> {
        self.data
    }
}

/// Prebuilt file drag payloads for one or more exported files.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FileDragPayloadData {
    uri_list: Vec<u8>,
    plain_file_list: Vec<u8>,
    gnome_copied_files: Vec<u8>,
}

impl FileDragPayloadData {
    pub(crate) fn from_validated(paths: Vec<PathBuf>) -> Self {
        Self {
            uri_list: file_uri_list(&paths),
            plain_file_list: plain_file_list(&paths),
            gnome_copied_files: gnome_copied_file_list(&paths),
        }
    }

    /// CRLF-delimited `file://` URI list.
    #[must_use]
    #[cfg(all(target_family = "unix", not(target_os = "macos")))]
    pub fn uri_list(&self) -> &[u8] {
        &self.uri_list
    }

    /// Newline-delimited native paths.
    #[must_use]
    #[cfg(all(target_family = "unix", not(target_os = "macos")))]
    pub fn plain_file_list(&self) -> &[u8] {
        &self.plain_file_list
    }

    /// `copy\nfile://...` payload for GNOME file managers.
    #[must_use]
    #[cfg(all(target_family = "unix", not(target_os = "macos")))]
    pub fn gnome_copied_files(&self) -> &[u8] {
        &self.gnome_copied_files
    }

    /// Build all standard file drag MIME offers.
    #[must_use]
    pub fn offers(&self) -> Vec<FileDragOffer> {
        vec![
            FileDragOffer::new(MIME_TEXT_URI_LIST, self.uri_list.clone()),
            FileDragOffer::new(MIME_TEXT_URI_LIST_UTF8, self.uri_list.clone()),
            FileDragOffer::new(MIME_TEXT_X_URI, self.uri_list.clone()),
            FileDragOffer::new(MIME_KDE_URI_LIST, self.uri_list.clone()),
            FileDragOffer::new(MIME_GNOME_COPIED_FILES, self.gnome_copied_files.clone()),
            FileDragOffer::new(MIME_TEXT_PLAIN_UTF8, self.plain_file_list.clone()),
            FileDragOffer::new(MIME_TEXT_PLAIN, self.plain_file_list.clone()),
        ]
    }
}

/// Build a CRLF-delimited `text/uri-list` payload.
#[must_use]
pub fn file_uri_list(paths: &[PathBuf]) -> Vec<u8> {
    let mut output = String::new();
    for path in paths {
        output.push_str(&file_uri(path));
        output.push_str("\r\n");
    }
    output.into_bytes()
}

/// Build a GNOME/Nautilus copied-files payload.
#[must_use]
pub fn gnome_copied_file_list(paths: &[PathBuf]) -> Vec<u8> {
    let mut output = String::from("copy\n");
    for path in paths {
        output.push_str(&file_uri(path));
        output.push('\n');
    }
    output.into_bytes()
}

/// Build a newline-delimited native path list.
#[must_use]
pub fn plain_file_list(paths: &[PathBuf]) -> Vec<u8> {
    let mut output = String::new();
    for (index, path) in paths.iter().enumerate() {
        if index > 0 {
            output.push('\n');
        }
        output.push_str(&path.to_string_lossy());
    }
    output.into_bytes()
}

/// Convert a path to a percent-encoded `file://` URI.
#[must_use]
pub fn file_uri(path: &Path) -> String {
    let path = path.to_string_lossy();
    let mut uri = String::from("file://");
    if !path.starts_with('/') {
        uri.push('/');
    }
    uri.push_str(&utf8_percent_encode(&path, URI_ESCAPE).to_string());
    uri
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_offers_include_uri_and_plain_payloads() {
        let payload = FileDragPayloadData::from_validated(vec![PathBuf::from(
            "/tmp/plugin take.flac",
        )]);

        let offers = payload.offers();

        assert_eq!(offers.len(), FILE_DRAG_OFFER_COUNT);
        assert!(offers.iter().any(|offer| {
            offer.mime_type() == MIME_TEXT_URI_LIST
                && offer.data() == b"file:///tmp/plugin%20take.flac\r\n"
        }));
        assert!(
            offers
                .iter()
                .any(|offer| offer.mime_type() == MIME_TEXT_PLAIN
                    && offer.data() == b"/tmp/plugin take.flac")
        );
        assert!(offers.iter().any(|offer| {
            offer.mime_type() == MIME_GNOME_COPIED_FILES
                && offer.data() == b"copy\nfile:///tmp/plugin%20take.flac\n"
        }));
    }
}
